// <auto-generated />
using System;
using LexHack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LexHack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921153752_InitialSqliteCreate")]
    partial class InitialSqliteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LexHack.Api.Data.AuditResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.ToTable("AuditResults");
                });

            modelBuilder.Entity("LexHack.Api.Data.AuditRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditRuns");
                });

            modelBuilder.Entity("LexHack.Api.Data.Playbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playbooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Standard Vendor NDA"
                        });
                });

            modelBuilder.Entity("LexHack.Api.Data.PlaybookRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaybookId");

                    b.ToTable("PlaybookRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClauseType = "governing_law",
                            Operator = "Equals",
                            PlaybookId = 1,
                            Severity = "Critical",
                            TargetValue = "South Africa"
                        },
                        new
                        {
                            Id = 2,
                            ClauseType = "liability_cap_amount",
                            Operator = "LessThanOrEqual",
                            PlaybookId = 1,
                            Severity = "Warning",
                            TargetValue = "500000"
                        },
                        new
                        {
                            Id = 3,
                            ClauseType = "is_indemnification_mutual",
                            Operator = "Equals",
                            PlaybookId = 1,
                            Severity = "Critical",
                            TargetValue = "true"
                        },
                        new
                        {
                            Id = 4,
                            ClauseType = "non_solicitation_months",
                            Operator = "LessThanOrEqual",
                            PlaybookId = 1,
                            Severity = "Warning",
                            TargetValue = "12"
                        },
                        new
                        {
                            Id = 5,
                            ClauseType = "unilateral_termination_days",
                            Operator = "GreaterThanOrEqual",
                            PlaybookId = 1,
                            Severity = "Critical",
                            TargetValue = "30"
                        });
                });

            modelBuilder.Entity("LexHack.Api.Data.AuditResult", b =>
                {
                    b.HasOne("LexHack.Api.Data.AuditRun", null)
                        .WithMany("Results")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexHack.Api.Data.PlaybookRule", b =>
                {
                    b.HasOne("LexHack.Api.Data.Playbook", null)
                        .WithMany("Rules")
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexHack.Api.Data.AuditRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("LexHack.Api.Data.Playbook", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
