version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - db
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LexHackPassword123!"
    ports:
      - "1433:1433"